---
name: Nextcloud installation - fpm
author: Danilo Jesic <danilo@green-coding.berlin>
version: 1
compose-file: !include compose.yml

services:
  gcb-puppeteer:
    image: greencoding/puppeteer-chrome
    setup-commands:
      - cp /tmp/repo/nextcloud_install.js /var/www/nextcloud_install.js
    networks:
      - nextcloud-setup-network
  # We don't need the volumes are we don't want to persist any data
  db:
    volumes: []
    networks:
      - nextcloud-setup-network

  app:
    volumes: []
    networks:
      - nextcloud-setup-network
  
  web:
    networks:
      - nextcloud-setup-network

networks:
  - nextcloud-setup-network

flow:
  - name: Check Website
    container: gcb-puppeteer
    commands:
      - type: console
        command: node /var/www/nextcloud_install.js
        note: Starting Puppeteer Flow
        parse-stdout-as-note: true
