---
name: Wordpress Data Puppeteer Scenario
author: Arne Tarara
version: 1

services:
  gcb-wordpress-mariadb:
    image: gcb_wordpress_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - 3306:3306
# This command is needed, cause the container needs a bootup time to work
    setup-commands:
      - sleep 20
    networks:
      - gcb-wordpress-mariadb-network
  gcb-wordpress-apache:
    image: gcb_wordpress_apache
    environment:
      WORDPRESS_DB_HOST: gcb-wordpress-mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 9875:9875
    networks:
      - gcb-wordpress-mariadb-network
    folder-destination: "/tmp/repo"
  gcb-puppeteer:
    image: greencoding/puppeteer-chrome
    setup-commands:
      - cp /tmp/repo/puppeteer-flow.js /var/www/puppeteer-flow.js
    networks:
      - gcb-wordpress-mariadb-network
flow:
  - name: Check Website
    container: gcb-puppeteer
    commands:
      - type: console
        command: node /var/www/puppeteer-flow.js
        note: Starting Puppeteer Flow
        read-notes-stdout: true
      - type: console
        command: sleep 30
        note: Idling
      - type: console
        command: node /var/www/puppeteer-flow.js
        note: Starting Puppeteer Flow again
        read-notes-stdout: true

networks:
  gcb-wordpress-mariadb-network:
