version: '2'
services:
  gcb-mariadb:
    build: .
    image: gcb_mariadb
    container_name: gcb-mariadb
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - 3306
    networks:
      - gcb-mariadb-wordpress-network
  gcb-wordpress:
    image: wordpress:latest
    container_name: gcb-wordpress
    environment:
      WORDPRESS_DB_HOST: gcb-mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    ports:
      - 9875:9875
    restart: always
    depends_on:
      - gcb-mariadb
    volumes:
      - ./wordpress.conf:/etc/apache2/sites-enabled/wordpress.conf:ro
    networks:
      - gcb-mariadb-wordpress-network

networks:
  gcb-mariadb-wordpress-network:
