---
name: NextCloud
author: Didi Hoffmann <didi@green-coding.berlin>
version: 1
compose-file: !include compose.yml

services:
  gcb-puppeteer:
    privileged: true
    image: greencoding/puppeteer-chrome
    container_name: gcb-puppeteer-chrome
    environment:
      - DISPLAY=:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    setup-commands:
      - cp /tmp/repo/nextcloud-usage.js /var/www/nextcloud-usage.js
    networks:
      - nextcloud-setup-network
  # We don't need the volumes are we don't want to persist any data
  db:
    # volumes: []
    networks:
      - nextcloud-setup-network

  app:
    # volumes: []
    setup-commands:
      - cp -R /tmp/nextcloud-data/* /var/www/html/
      - chown -R www-data /var/www/html/
    networks:
      - nextcloud-setup-network

networks:
  - nextcloud-setup-network

flow:
  - name: Check Website
    container: gcb-puppeteer
    commands:
      - type: console
        command: node /var/www/nextcloud-usage.js
        note: Starting Puppeteer Flow
        parse-stdout-as-note: true
