---
name: Django test container
author: Didi Hoffmann
version: 1
architecture: linux

services:
  gcb-django-tests:
    image: gcb_django_tests

flow:
  - name: Django test
    container: gcb-django-tests
    commands:
      - type: console
        command: bash /tmp/django/tests/runner.sh
        note: Starting the django tests
