version: '2'
services:
  gcb-xdotool:
    build: .
    container_name: gcb-xdotool
    image: gcb_xdotool
    restart: always
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
    environment:
# If you have multiple displays please change this to the entry you want under /tmp/X11-unix
      DISPLAY: ":1"
