name: Linting tools comparison - Ruff
author: Danilo Jesic <danilo@green-coding.berlin>
version: 1
description: Lint the dev branch of green-metrics-tool using ruff


services:
  linting:
    image: gcb_lint
    build:
      context: .
      dockerfile: Dockerfile


flow:
  - name: Linting
    container: linting
    commands:
      - type: console
        command: /tmp/linting/venv/bin/python3 -m ruff --config /tmp/src/pyproject.toml /tmp/linting/
        note: Linting with Ruff
        ignore-errors: true  # We expect some linting errors to occur