name: Pylint
author: Danilo Jesic <danilo@green-coding.berlin>
version: 1
description: Lint our repo from the dev branch


services:
  linting:
    image: gcb_lint
    build: .


flow:
  - name: Ruff linting
    container: linting
    commands:
      - type: console
        command: /tmp/linting/venv/bin/python3 -m pylint --rcfile /tmp/src/.pylintrc -j 0 /tmp/linting/*.py
        note: Lint
        ignore-errors: true  # We expect some linting errors to occur
