---
name: Hugo Static Site
author: Arne Tarara <arne@green-coding.berlin>
version: 1

services:
  gcb-hugo-apache:
    image: httpd
    networks:
      - gcb-hugo-apache-network
    setup-commands:
      - cp -R /tmp/repo/htdocs /usr/local/apache2/
  gcb-curl:
    image: curlimages/curl
    networks:
      - gcb-hugo-apache-network
    cmd: sh

flow:
  - name: Check Website
    container: gcb-curl
    commands:
      - type: console
# Set curl to silent, otherwise the STDERR speed report bothers us
        command: curl -s gcb-hugo-apache
        note: Starting curl

networks:
  gcb-hugo-apache-network:
