---
name: Hugo Static Site
author: Arne Tarara <arne@green-coding.berlin>
description: Curl the hugo server

services:
  gcb-hugo-apache:
    image: httpd
    networks:
      - gcb-hugo-apache-network
    setup-commands:
      - cp -R /tmp/repo/htdocs /usr/local/apache2/
  gcb-curl:
    # Newer version of the curl image lead to an error with Docker rootless https://github.com/curl/curl-container/issues/55
    image: curlimages/curl:8.1.0
    networks:
      - gcb-hugo-apache-network
    command: sh

flow:
  - name: Check Website
    container: gcb-curl
    commands:
      - type: console
# Set curl to silent, otherwise the STDERR speed report bothers us
        command: curl -s gcb-hugo-apache
        note: Starting curl

networks:
  gcb-hugo-apache-network:
