---
name: SCI with number crunching
author: Arne Tarara <arne@green-coding.berlin>
description: A simple sysbench run that outputs its performance as SCI metric

services:
  gcb-alpine-sysbench:
    image: alpine
    setup-commands:
      - command: apk add sysbench coreutils gawk

custom_metrics:
  calculated_prime_numbers:
    unit: CPN
    sci: True

flow:
  - name: Stress
    container: gcb-alpine-sysbench
    commands:
      - type: console
        note: Starting sysbench
        command: sysbench --cpu-max-prime=25000 --threads=1 --time=3 cpu run --debug=off | gawk '/total number of events:/ {cmd="date +%s%N"; cmd | getline ts; close(cmd); print ts " calculated_prime_numbers=" $NF}'
        shell: sh
