services:
  puppeteer-chrome:
    privileged: true
    image: greencoding/puppeteer-chrome
    container_name: puppeteer-chrome
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./puppeteer-image-test-chrome.js:/var/www/puppeteer-image-test-chrome.js
  puppeteer-firefox:
    image: greencoding/puppeteer-firefox
    container_name: puppeteer-firefox
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./puppeteer-image-test-firefox.js:/var/www/puppeteer-image-test-firefox.js
