---
name: Firefox non headless test
author: Arne Tarara
version: 1
architecture: linux

services:
  gcb-wordpress:
    image: wordpress
    networks:
      - firefox-headless
  gcb-puppeteer:
    image: greencoding/puppeteer-firefox
    setup-commands:
      - cp /tmp/repo/puppeteer-flow.js /var/www/puppeteer-flow.js
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
# If you have multiple displays please change this to the entry you want under /tmp/X11-unix
      DISPLAY: ":0"
    networks:
      - firefox-headless

flow:
  - name: Check Website
    container: gcb-puppeteer
    commands:
      - type: console
        command: node /var/www/puppeteer-flow.js
        note: Starting Puppeteer Flow
        read-notes-stdout: true

networks:
  firefox-headless: