[tool.ruff]

# Assume Python 3.10.
target-version = "py310"

# Maximum number of characters on a single line.
line-length = 120
# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

select = [ 
 "PLE1142",
 "PLE1310",
 "PLE1307",
 "PLE2502",
 "PLE0116",
 "F502",
 "PLE0605",
 "PLE0604",
 "PLE2510",
 "PLE2513",
 "PLE2514",
 "PLE2512",
 "PLE2515",
 "PLE1206",
 "PLE1205",
 "F524",
 "F506",
 "N805",
 "N805",
 "B002",
 "PLE0117",
 "F701",
 "F702",
 "F901",
 "PLE0101",
 "F706",
 "E999",
 "F501",
 "F821",
 "PLE0118",
 "F704",
 "W605",
 "PLW0129",
 "F631",
 "E722",
 "PLW0711",
 "B023",
 "SIM108",
 "B006",
 "B014",
 "F601",
 "B018",
 "F541",
 "T100",
 "PLW0603",
 "PLW0602",
 "PLW1508",
 "F404",
 "B018",
 "A001",
 "ARG001",
 "F507",
 "F504",
 "F401",
 "F841",
 "PLW0120",
 "F403",
 "N804",
 "Q002",
 "SIM110",
 "D210",
 "D419",
 "N815",
 "E501",
 "SIM300",
 "D101",
 "W292",
 "D103",
 "D100",
 "E401",
 "E711",
 "E712",
 "UP034",
 "I001",
 "E721",
 "PLC0414",
 "I001",
 "E402",
 "PLR0133",
 "UP007",
 "PLR1701",
 "UP006",
 "C402",
 "C417",
 "SIM401",
 "C401",
 "PLR1722",
 "SIM108",
 "PLR5501",
 "RET501",
 "RET502",
 "F632",
 "PLR2004",
 "UP008",
 "C901",
 "PLR0912",
 "PLR0911",
 "PLR0915",
 "COM818",
 "C417",
 "C406",
 "C405",
 "UP004",
 "PLR1711"
]

ignore = ["ALL"]
# Allow autofix for all enabled rules (when `--fix`) is provided.
# fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]
unfixable = []



# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "/tmp/linting/metric_providers/psu/energy/ac/xgboost/machine/model/*"  # git submodule
]

[tool.ruff.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
