---
name: Wordpress Basic Playwright Scenario
author: Arne Tarara <arne@green-coding.io>
description: Simple Wordpress where just the Homepage with the install instructions is accessed. Mostly used for testing wordpress build and startup times.
compose-file: !include compose.yml

services:
  gcb-puppeteer:
    image: greencoding/gcb_playwright:v16
    networks:
      - gcb-mariadb-wordpress-network

flow:
  - name: Check Website
    container: gcb-puppeteer
    commands:
      - type: console
        command: python3 /tmp/repo/wordpress-official-starter/playwright-flow.py
        note: Starting User Journey
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true
