---
name: Wordpress Basic Puppeteer Scenario
author: Arne Tarara <arne@green-coding.berlin>
description: Simple Wordpress where just the Homepage with the install instructions is accessed. Mostly used for testing wordpress build and startup times.
compose-file: !include compose.yml

services:
  gcb-puppeteer:
    image: greencoding/puppeteer-chrome
    setup-commands:
      - cp /tmp/repo/puppeteer-flow.js /var/www/puppeteer-flow.js
    networks:
      - gcb-mariadb-wordpress-network

flow:
  - name: Check Website
    container: gcb-puppeteer
    commands:
      - type: console
        command: node /var/www/puppeteer-flow.js
        note: Starting Puppeteer Flow
        read-notes-stdout: true
        log-stdout: true


