---
name: Wordpress Basic Puppeteer Scenario
author: Arne Tarara
version: 1
compose-file: !include compose.yml

services:
  gcb-puppeteer:
    image: greencoding/puppeteer-chrome
    setup-commands:
      - cp /tmp/repo/puppeteer-flow.js /var/www/puppeteer-flow.js
    networks:
      - gcb-mariadb-wordpress-network
  gcb-mariadb:
    networks:
      - gcb-mariadb-wordpress-network
  gcb-wordpress:
    networks:
      - gcb-mariadb-wordpress-network
    volumes:
      - ./wordpress_two.conf:/etc/apache2/sites-enabled/wordpress.conf:ro
flow:
  - name: Check Website
    container: gcb-puppeteer
    commands:
      - type: console
        command: node /var/www/puppeteer-flow.js
        note: Starting Puppeteer Flow
        parse-stdout-as-note: true

networks:
  gcb-mariadb-wordpress-network:
