---
name: NextCloud Firefox MariaDB
author: Didi Hoffmann <didi@green-coding.berlin>
version: 1
description: Installs the official NextCloud image and creates an user and event
compose-file: !include compose.yml


services:
  gcb-puppeteer:
    image: greencoding/puppeteer-firefox
    setup-commands:
      - cp /tmp/repo/nextcloud_install_puppeteer.js /var/www/nextcloud_install_puppeteer.js
      - cp /tmp/repo/nextcloud_create_event_puppeteer.js /var/www/nextcloud_create_event_puppeteer.js
    networks:
      - nextcloud-setup-network
    # volumes:
    #   - /tmp/.X11-unix:/tmp/.X11-unix
    # environment:
    #   DISPLAY: ":0"

  db:
    volumes: []
    networks:
      - nextcloud-setup-network

  app:
    # This is all that is needed to build a docker file and use it in your benchmark
    image: gcb_nextcloud
    #build: .
    volumes: []
    networks:
      - nextcloud-setup-network

networks:
  - nextcloud-setup-network

flow:
  - name: Check Website
    container: gcb-puppeteer
    commands:
      - type: console
        command: node nextcloud_install_puppeteer.js
        note: Installing Nextcloud
        parse-stdout-as-note: true
      - type: console
        command: node nextcloud_create_event_puppeteer.js
        note: Creating Event
        parse-stdout-as-note: true
