---
name: Idle Container for 5 Seconds
author: Arne Tarara <arne@green-coding.berlin>
version: 1
description: Idle the container for 5 seconds

services:
  gcb-idle:
    image: alpine
    cmd: sh

flow:
  - name: Idle
    container: gcb-idle
    commands:
      - type: console
        command: sleep 5
        note: Starting Sleep
