---
name: Test-Scenario
author: Arne Tarara
version: 1
architecture: linux

services:
  gcb-ml-model:
    image: gcb_ml_model

flow:
  - name: Load 1000
    container: gcb-ml-model
    commands:
      - type: console
        command: python3 /tmp/hyperparameter_tuning.py
        read-notes-stdout: true
  